# Logo Url
# Please enter the absolute path to your logo file
# or remove the following line with replacing logo-header.png with your own logo
logo: http://ppoffice.github.io/hexo-theme-hueman/css/images/logo-header.png

# Header
menu:
  Home: /
  Bylaws: /bylaws
# Categories:
  About: /about/index.html

# Article list grouped by year
groupByYear: true

# Content
fancybox: true

# Thumbnail
thumbnail: false

# Scroll Loading
scrollLoading: true

# Sidebar
sidebar: left // sidebar's position (left or right)
#social_links:
#  twitter:
#  facebook:
#  google_plus:
#  github: https://github.com/ppoffice/hexo-theme-hueman
#  weibo:
#  rss: /atom.xml
widgets:
- recent_posts
- category
- archive
- tag
- tagcloud
- links

# Links
links:
  MODG Homepage: https://motherofdivinegrace.org/
  MODG NHS Slack: https://modg-nhs.slack.com/

# Don't use Google APIs if you are in google-blocked areas
use_google_apis: false

# Miscellaneous
#google_analytics:
favicon: /favicon.png
#fb_admins:
#fb_app_id:
